### ISSUE TITLE
Disk write failure

### ISSUE THREAD

**Issue by MoryCorp** [CanadaBry/ValheimDocker#2]
Hi thanks for your work.
Just tried to launch it and docker logs returns :

```WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Downloading update (0 of 16403 KB)...
[  0%] Downloading update (636 of 16403 KB)...
[  3%] Downloading update (2559 of 16403 KB)...
[ 15%] Downloading update (4646 of 16403 KB)...
[ 28%] Downloading update (5868 of 16403 KB)...
[ 35%] Downloading update (7095 of 16403 KB)...
[ 43%] Downloading update (8316 of 16403 KB)...
[ 50%] Downloading update (9543 of 16403 KB)...
[ 58%] Downloading update (10900 of 16403 KB)...
[ 66%] Downloading update (12122 of 16403 KB)...
[ 73%] Downloading update (13355 of 16403 KB)...
[ 81%] Downloading update (14606 of 16403 KB)...
[ 89%] Downloading update (15845 of 16403 KB)...
[ 96%] Downloading update (16403 of 16403 KB)...
[100%] Download complete.
[----] Installing update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
ERROR! Failed to install app '896660' (Disk write failure)
cp: cannot create regular file '/home/steam/server_data/steamclient.so': Permission denied
/home/steam/server_scripts/server.sh: line 25: /home/steam/server_data/valheim_server.x86_64: No such file or directory
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
ERROR! Failed to install app '896660' (Disk write failure)
cp: cannot create regular file '/home/steam/server_data/steamclient.so': Permission denied
/home/steam/server_scripts/server.sh: line 25: /home/steam/server_data/valheim_server.x86_64: No such file or directory
```

May you help me ? :)

**Comment by MoryCorp** [comment]
Error happened because I unquoted the volume mount.
Then the server_data blongs to root and not steam user

**Comment by CanadaBry** [comment]
The issue is because when docker makes the volumes for you, it is owned by root with only read/execute permissions.

You can either `chmod +w` those directories so that the image can write there or delete and recreate the directories (essentially the same thing as adding write permissions but your user will own the directory).

Personally, whenever I am mounting a volume for docker I pre-create the directories myself, so I don't often run into this issue. 

Let me know if any of this helps.

**Comment by pkshetlie** [comment]
I get the same, even i do the chmod +w :(

**Comment by MoryCorp** [comment]
Thanks for the fast answer.
I did recreate the directories and same error

![image](https://user-images.githubusercontent.com/26336203/107080650-e0217380-67f1-11eb-890b-2db8befa7a7a.png)

`Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
ERROR! Failed to install app '896660' (Disk write failure)
cp: cannot create regular file '/home/steam/server_data/steamclient.so': Permission denied
/home/steam/server_scripts/server.sh: line 25: /home/steam/server_data/valheim_server.x86_64: No such file or directory
`

**Comment by MoryCorp** [comment]
![image](https://user-images.githubusercontent.com/26336203/107081074-6ccc3180-67f2-11eb-9286-191c6d658abc.png)
steam uid is 1000, server_data belongs to 1001 and docker-compose specify 1002 is that related ?

**Comment by aaroncouch** [comment]
@MoryCorp 

I was having the same exact issue. Could you try the following:

Delete both mount dirs on the host (data & scripts)
Create both mount dirs on the host manually and run `chmod +w` on both
Within the `docker-compose.yml` file make sure that you specific absolute path of both directories.

I really hope that helps. I've got the container running right now with the volumes mounted etc.

**Comment by MoryCorp** [comment]
All steps
```
holory@vps645530:~/apps/valheim$ rm -r data/
holory@vps645530:~/apps/valheim$ rm -r scripts/
holory@vps645530:~/apps/valheim$ ls
docker-compose.yml  Dockerfile  server.sh
holory@vps645530:~/apps/valheim$ mkdir data
holory@vps645530:~/apps/valheim$ mkdir scripts
holory@vps645530:~/apps/valheim$ ls -l
total 20
drwxrwxr-x 2 holory holory 4096 Feb  5 20:49 data
-rw-rw-r-- 1 holory holory  563 Feb  5 20:43 docker-compose.yml
-rw-rw-r-- 1 holory holory  793 Feb  5 18:51 Dockerfile
drwxrwxr-x 2 holory holory 4096 Feb  5 20:49 scripts
-rw-rw-r-- 1 holory holory  907 Feb  5 18:27 server.sh
holory@vps645530:~/apps/valheim$ chmod +w data/
holory@vps645530:~/apps/valheim$ chmod +w scripts/
holory@vps645530:~/apps/valheim$ ls -l
total 20
drwxrwxr-x 2 holory holory 4096 Feb  5 20:49 data
-rw-rw-r-- 1 holory holory  563 Feb  5 20:43 docker-compose.yml
-rw-rw-r-- 1 holory holory  793 Feb  5 18:51 Dockerfile
drwxrwxr-x 2 holory holory 4096 Feb  5 20:49 scripts
-rw-rw-r-- 1 holory holory  907 Feb  5 18:27 server.sh
```
docker-compose :

```
version: '3.3'
services:
    valheim:
        image: wilso224/valheim_dedicated_server
        container_name: valheim
        volumes:
            - './data:/home/steam/server_data'
            - './scripts:/home/steam/.config/unity3d/IronGate/Valheim'
        ports:
            - '0.0.0.0:2456:2456/udp'
            - '0.0.0.0:2457:2457/udp'
            - '0.0.0.0:2458:2458/udp'
        environment:
            - PUID=1002
            - PGID=1002
            - SERVER_NAME="Valheim Docker"
            - SERVER_PORT=2456
            - SERVER_PASSWORD=secret
```

Same error

**Comment by aaroncouch** [comment]
These two lines:

'./data:/home/steam/server_data'
'./scripts:/home/steam/.config/unity3d/IronGate/Valheim'

Can you try absolute path? For instance on my host:

```
        volumes:
            - '/home/aaron/Desktop/ValheimDocker/server/data:/home/steam/server_data'
            - '/home/aaron/Desktop/ValheimDocker/server/scripts:/home/steam/.config/unity3d/IronGate/Valheim'
```

**Comment by MoryCorp** [comment]
Tried with :

 ```
version: '3.3'
services:
    valheim:
        image: wilso224/valheim_dedicated_server
        container_name: valheim
        volumes:
            - '/home/holory/apps/valheim/data:/home/steam/server_data'
            - '/home/holory/apps/valheim/scripts:/home/steam/.config/unity3d/IronGate/Valheim'
        ports:
            - '0.0.0.0:2456:2456/udp'
            - '0.0.0.0:2457:2457/udp'
            - '0.0.0.0:2458:2458/udp'
        environment:
            - PUID=1002
            - PGID=1002
            - SERVER_NAME="Valheim Docker"
            - SERVER_PORT=2456
            - SERVER_PASSWORD=secret
```

Same
