### ISSUE TITLE
Disk Failure #2

### ISSUE THREAD

**Issue by MoryCorp** [CanadaBry/ValheimDocker#9]
Opening a new issue as all files changed.

![image](https://user-images.githubusercontent.com/26336203/107699535-84099400-6cb6-11eb-964a-0b2180a10419.png)

Inside valheim directory

![image](https://user-images.githubusercontent.com/26336203/107699562-8b30a200-6cb6-11eb-9012-d6b645a39b30.png)

docker-compose.yml : 

```
version: '3.3'
services:
    valheim:
        image: wilso224/valheim_dedicated_server
        container_name: valheim
        volumes:
            - '/home/holory/apps/valheim_sever/valheim:/home/steam/valheim'
        ports:
            - '2456:2456/udp'
            - '2457:2457/udp'
            - '2458:2458/udp'
        environment:
            - SERVER_NAME=Holory
            - SERVER_PORT=2456
            - SERVER_PASSWORD=morycorp
            - SERVER_WORLD=Holory
            - PUID=1000
            - PGID=1000
```

Dockerfile : 

```
FROM debian:buster

# download requirements
RUN apt-get -y update && \
    apt-get -y install lib32gcc1 lib32stdc++6 curl && \
    apt-get clean && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/

# setup steam user
RUN useradd -m steam
WORKDIR /home/steam

COPY server.sh .

# download steamcmd
RUN mkdir steamcmd && cd steamcmd && \
    curl "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -

# start steamcmd to force it to update itself
RUN ./steamcmd/steamcmd.sh +quit && \
    mkdir -pv /home/steam/.steam/sdk32/ && \
    ln -s /home/steam/steamcmd/linux32/steamclient.so /home/steam/.steam/sdk32/steamclient.so

# start the server main script
ENTRYPOINT ["bash", "/home/steam/server.sh"]
```

server.sh

```
#!/bin/bash

PUID=${PUID:-1000}
PGID=${PGID:-1000}

usermod -u ${PUID} steam
groupmod -g ${PGID} steam
su -s /bin/bash -c 'id' steam

# update server's data
/home/steam/steamcmd/steamcmd.sh \
	    +login anonymous \
	        +force_install_dir /home/steam/valheim/server \
		    +app_update 896660 \
		        +exit

#Copy 64bit steamclient, since it keeps using 32bit
cp /home/steam/steamcmd/linux64/steamclient.so /home/steam/valheim/server/

#Apply default values for server if not set
SERVER_NAME=${SERVER_NAME:-My\ server}
SERVER_PORT=${SERVER_PORT:-2456}
SERVER_WORLD=${SERVER_WORLD:-Dedicated}
SERVER_PASSWORD=${SERVER_PASSWORD:-secret}

#Launch server
export LD_LIBRARY_PATH=./linux64:$LD_LIBRARY_PATH
export SteamAppId=892970
/home/steam/valheim/server/valheim_server.x86_64 -name "$SERVER_NAME" -port $SERVER_PORT -world "$SERVER_WORLD" -password "$SERVER_PASSWORD" -savedir "/home/steam/valheim/data" -public 1 &

#Trap Container Stop for graceful exit
trap "kill -SIGINT $!;" SIGTERM

#Wait for server to exit
while wait $!; [ $? != 0 ]; do true; done
```

Please tell me what I am doing wrong @CanadaBry @InB4DevOps
